added verification

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -37,3 +37,29 @@ jobs:
 
             echo "Deployment completed successfully"
           EOF
+
+      - name: Verify Deployment
+        run: |
+          echo "Waiting for containers to start..."
+          sleep 10
+
+          echo "Checking the server availability..."
+          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://192.168.1.120)
+
+          if [ "$HTTP_STATUS" -ne 200 ]; then
+            echo "Error: Returned HTTP $HTTP_STATUS instead of 200"
+            exit 1
+          fi
+          echo "Service is available"
+
+          echo "Checking the Nginx configuration..."
+          SERVER_HEADER=$(curl -s -I http://192.168.1.120 | grep -i "^Server:")
+
+          if [[ "$SERVER_HEADER" != *"nginx"* ]]; then
+            echo "Error: Server header does not contain 'nginx'."
+            exit 1
+          fi
+          echo "Nginx is running and configured correctly."
+
+          echo "Verification completed!"
+
